version: "3.8"
services:
  CE7490_P1:
    image: phatli/ce7490_p1
    stdin_open: true
    tty: true
    ipc: host
    user: "${UID}:${GID}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - type: bind
        source: ./
        target: /home/user/ce7490_proj1
    dns:
      - 8.8.8.8